package grafica;

/**
 * Clase para testear propiedades de la clase File
 * @author  Ing. Valerio Frittelli
 * @version Marzo de 2008
 */
import java.io.*;
import javax.swing.*;
import principal.*;

public class Ventana extends javax.swing.JFrame
{
    private JFileChooser jfd = new JFileChooser();
    private File f;
    private int porcentaje;
    private int pCompletado;
    private Compresor comp = new Compresor();
    
    /** Creates new form VentanaInicial */
    public Ventana()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArchComprimir = new javax.swing.JButton();
        btnDescomprimir = new javax.swing.JButton();
        jpbProgreso = new javax.swing.JProgressBar();
        btnComprimir = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();
        txtRutaDescomprimir = new javax.swing.JTextField();
        lblRutaDestino = new javax.swing.JLabel();
        lblRutaComprimir = new javax.swing.JLabel();
        txtRutaComprimir = new javax.swing.JTextField();
        lblProgreso = new javax.swing.JLabel();
        btnArchDescomprimir = new javax.swing.JButton();
        mnuMenu = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();
        mnuAcciones = new javax.swing.JMenu();
        explorar = new javax.swing.JMenuItem();
        codificar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Uso de la clase File");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        btnArchComprimir.setText("Archivo a comprimir");
        btnArchComprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchComprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnArchComprimir);
        btnArchComprimir.setBounds(10, 10, 150, 23);

        btnDescomprimir.setText("Descomprimir");
        btnDescomprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescomprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDescomprimir);
        btnDescomprimir.setBounds(170, 110, 130, 23);
        getContentPane().add(jpbProgreso);
        jpbProgreso.setBounds(10, 220, 460, 18);

        btnComprimir.setText("Comprimir");
        btnComprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprimir);
        btnComprimir.setBounds(170, 10, 130, 23);

        btnDetener.setText("Frenar proceso");
        btnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetenerActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetener);
        btnDetener.setBounds(330, 80, 130, 23);

        txtRutaDescomprimir.setEditable(false);
        getContentPane().add(txtRutaDescomprimir);
        txtRutaDescomprimir.setBounds(10, 160, 290, 20);

        lblRutaDestino.setText("Ruta de destino:");
        getContentPane().add(lblRutaDestino);
        lblRutaDestino.setBounds(10, 140, 290, 20);

        lblRutaComprimir.setText("Ruta de origen:");
        getContentPane().add(lblRutaComprimir);
        lblRutaComprimir.setBounds(10, 40, 290, 20);

        txtRutaComprimir.setEditable(false);
        getContentPane().add(txtRutaComprimir);
        txtRutaComprimir.setBounds(10, 60, 290, 20);

        lblProgreso.setText("Progreso...");
        getContentPane().add(lblProgreso);
        lblProgreso.setBounds(10, 200, 80, 14);

        btnArchDescomprimir.setText("Archivo a descomprimir");
        btnArchDescomprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchDescomprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnArchDescomprimir);
        btnArchDescomprimir.setBounds(10, 110, 150, 23);

        mnuArchivo.setText("Archivo");

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        mnuArchivo.add(salir);

        mnuMenu.add(mnuArchivo);

        mnuAcciones.setText("Acciones");

        explorar.setText("Abrir...");
        explorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explorarActionPerformed(evt);
            }
        });
        mnuAcciones.add(explorar);

        codificar.setText("Comprimir");
        codificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codificarActionPerformed(evt);
            }
        });
        mnuAcciones.add(codificar);

        jMenuItem1.setText("Descomprimir");
        mnuAcciones.add(jMenuItem1);

        mnuMenu.add(mnuAcciones);

        setJMenuBar(mnuMenu);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-489)/2, (screenSize.height-303)/2, 489, 303);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescomprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescomprimirActionPerformed
        if(txtRutaDescomprimir.getText().trim().length() == 0 )
        {
            JOptionPane.showMessageDialog(this, "Seleccione antes un archivo para descomprimir", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else 
        {
            comp.descomprimir(txtRutaDescomprimir.getText());
        }
        limpiar();
}//GEN-LAST:event_btnDescomprimirActionPerformed

    private void explorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explorarActionPerformed
        limpiar();
       
    }//GEN-LAST:event_explorarActionPerformed

    private void btnArchComprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchComprimirActionPerformed
        limpiar();
        seleccionar("comp");
}//GEN-LAST:event_btnArchComprimirActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void codificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codificarActionPerformed
        limpiar ();
    }//GEN-LAST:event_codificarActionPerformed

    private void btnComprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprimirActionPerformed
        if(txtRutaComprimir.getText().trim().length() == 0 )
        {
            JOptionPane.showMessageDialog(this, "Seleccione antes un archivo para comprimir", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            comp.comprimir(txtRutaComprimir.getText());
        }
        limpiar();
}//GEN-LAST:event_btnComprimirActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        // comp.interrupt();
}//GEN-LAST:event_btnDetenerActionPerformed

    private void btnArchDescomprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchDescomprimirActionPerformed
        limpiar();
        seleccionar("descomp"); 
}//GEN-LAST:event_btnArchDescomprimirActionPerformed
    
    /**
      * Clase que selecciona el archivo a comprimir / descomprimir
      * @author  Morales - Roldán - Senn
      * @version Mayo de 2008
      */
    private void seleccionar(String opcion)
    {
        this.setTitle("Seleccione el archivo: ");
        
        int r = jfd.showOpenDialog(this);
        if(r == JFileChooser.APPROVE_OPTION)
        {
            f = jfd.getSelectedFile();
            if (opcion.compareTo("comp") == 0)
            {
                txtRutaComprimir.setText(f.getAbsolutePath());
            }
            else
            {
                txtRutaDescomprimir.setText(f.getAbsolutePath());
            }
        }
    }
    
    /**
      * Clase para calcular el porcentaje de progreso en la codificación del archivo
      * @author  Morales - Roldán - Senn
      * @version Mayo de 2008
      */
    public void progreso(long actual, long tam)
    {
        porcentaje = (int) (actual * 100 / tam);
        if (porcentaje > pCompletado)
        {
            pCompletado = porcentaje;
            System.out.println("Completado %" + pCompletado);
            jpbProgreso.setValue(porcentaje);
        }
    }
    
    /**
      * Clase para setear los componentes a su estado inicial
      * @author  Morales - Roldán - Senn
      * @version Mayo de 2008
      */
    private void limpiar ()
    {
        txtRutaComprimir.setText("");
        txtRutaDescomprimir.setText("");
        // btnComprimir.setEnabled(false);
        // btnDescomprimir.setEnabled(false);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchComprimir;
    private javax.swing.JButton btnArchDescomprimir;
    private javax.swing.JButton btnComprimir;
    private javax.swing.JButton btnDescomprimir;
    private javax.swing.JButton btnDetener;
    private javax.swing.JMenuItem codificar;
    private javax.swing.JMenuItem explorar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JProgressBar jpbProgreso;
    private javax.swing.JLabel lblProgreso;
    private javax.swing.JLabel lblRutaComprimir;
    private javax.swing.JLabel lblRutaDestino;
    private javax.swing.JMenu mnuAcciones;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuBar mnuMenu;
    private javax.swing.JMenuItem salir;
    private javax.swing.JTextField txtRutaComprimir;
    private javax.swing.JTextField txtRutaDescomprimir;
    // End of variables declaration//GEN-END:variables
    
}
